version: "3.8"

services:
  api:
    depends_on:
      - db
    build: .
    # container_name: oeliks-server
    command: ./docker-entrypoint.sh dev
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
      # - DB_URL=mysql://root:pwd@localhost/oeliks_db
    ports:
      - 8000:8000
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    # restart: always
    environment:
      - MYSQL_DATABASE=oeliks_db
      - MYSQL_ROOT_PASSWORD=pwd
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
