version: "3.8"

services:
  web:
    container_name: oeliks-web
    depends_on:
      - server
    image: ghcr.io/dragonsteam/oeliks-front:latest
    # command: nginx -g daemon off
    ports:
      - 80:80
      - 443:443
    volumes:
      - media:/usr/share/nginx/media

  server:
    container_name: oeliks-server
    depends_on:
      - db
    image: ghcr.io/dragonsteam/oeliks-server:latest
    command: ./docker-entrypoint.sh
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      # - DB_URL=mysql://root:pwd@localhost/oeliks_db
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - media:/app/media

  db:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3306:3306
    # restart: always
    environment:
      - MYSQL_DATABASE=oeliks_db
      - MYSQL_ROOT_PASSWORD=pwd
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
  media:
