# Generated by Django 5.0.2 on 2024-02-23 06:18

import api.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='username')),
                ('phone', models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. 9 characters. numbers only.', max_length=9, unique=True, validators=[api.validators.UnicodePhoneValidator()])),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('uz-kr', 'Uzbek-Krilic'), ('ru', 'Russian'), ('en', 'English')], max_length=5, null=True)),
                ('role', models.CharField(choices=[('gue', 'Guest'), ('cli', 'Client'), ('adm', 'Admin')], max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, validators=[api.validators.UnicodeTitleValidator()])),
                ('about', models.CharField(blank=True, max_length=2048)),
                ('exchange_method', models.CharField(choices=[('p', 'priced'), ('e', 'exchange'), ('f', 'free')], max_length=1)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek Sums'), ('USD', 'US Dollars'), ('RUB', 'Russian Rubles')], max_length=3)),
                ('is_auto_renew', models.BooleanField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted')),
            ],
        ),
    ]
