# Generated by Django 5.0.2 on 2024-03-17 09:10

import api.validators
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='username')),
                ('phone', models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. 9 characters. numbers only.', max_length=9, unique=True, validators=[api.validators.UnicodePhoneValidator()])),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('uz-kr', 'Uzbek-Krilic'), ('ru', 'Russian'), ('en', 'English')], max_length=5, null=True)),
                ('role', models.CharField(choices=[('gue', 'Guest'), ('cli', 'Client'), ('adm', 'Admin')], max_length=3, null=True)),
                ('tg_id', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, validators=[api.validators.UnicodeTitleValidator()])),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('exchange_method', models.CharField(choices=[('p', 'priced'), ('e', 'exchange'), ('f', 'free')], max_length=1)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek Sums'), ('USD', 'US Dollars'), ('RUB', 'Russian Rubles')], max_length=3)),
                ('is_auto_renew', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad/images', validators=[api.validators.validate_file_size])),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_images', to='api.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_category', to='api.section')),
            ],
        ),
    ]
