# Generated by Django 5.0.2 on 2024-02-18 09:40

import api.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, validators=[api.validators.UnicodeTitleValidator()])),
                ('aboute', models.CharField(blank=True, max_length=2048)),
                ('price_method', models.CharField(choices=[('p', 'priced'), ('e', 'exchange'), ('f', 'free')], max_length=1)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek Sums'), ('USD', 'US Dollars'), ('RUB', 'Russian Rubles')], max_length=3)),
                ('is_auto_renew', models.BooleanField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted')),
            ],
        ),
    ]
