# Generated by Django 5.0.2 on 2024-02-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='aboute',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='price_method',
            new_name='exchange_method',
        ),
    ]
