# Generated by Django 5.0.2 on 2024-02-18 08:04

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. 9 characters. numbers only.', max_length=9, unique=True, validators=[api.validators.UnicodePhoneValidator()]),
        ),
    ]
