# Generated by Django 5.0.2 on 2024-03-03 17:17

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to='ad/images', validators=[api.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='TeleAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele_id', models.BigIntegerField()),
                ('photo_url', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teleauth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
