# Generated by Django 5.0.2 on 2024-03-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_tg_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeleAuth',
        ),
    ]
