# Generated by Django 5.0.2 on 2024-03-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_adimage_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='about',
            new_name='description',
        ),
    ]
