name: Docker Image CI

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dragonsteam/oeliks-server:latest

jobs:
  publish:
    name: publish image
    runs-on: self-hosted
    # runs-on: ubuntu:latest

    steps:
      - uses: actions/checkout@v3
      # - name: Login
      - run: |
          echo ${{secrets.PAT}} | docker login ghcr.io -u dragonsteam
          --password-stdin
      - name: Build and Publish
        run: |
          docker build . --file Dockerfile --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
